services:
  postgres_cadastro:
    container_name: postgres_cadastro_ifood
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "5432:5432"